name: ndcgws
channels:
    - pytorch
dependencies:
    - python=3.8
    - pytorch>=1.5
    - torchvision>=0.6
    - matplotlib
    - pandas
    - nltk
    - seaborn
    - scikit-learn
    - tensorboard
    - pip
    - pip:
        - python-Levenshtein 
